%{
#include "bscp.hpp"

#include <typeinfo>
#include <string>
#include <math.h>
#include <map>
#include <cstring>

#ifndef FLEXLEXER_H
#include <FlexLexer.h>
#endif

#include "lex.hpp"

extern yyFlexLexer* lexer;

bscp_obj* s_obj(bscp_obj* parent, bscp_value* first);
int bscp_eval(bscp_value* value);

// int yylex(yy::parser::value_type* value);
int yylex(yy::parser::value_type* value, yy::parser::location_type* location);

extern struct lex_token current_token;
extern const char* err_msg;
extern bscp_value* output;

#define require_true(expr, ...) \
    do { \
        if(!(expr)) { \
            fprintf(stderr, __VA_ARGS__); \
            errno = 1; \
            YYERROR; \
        } \
    } while(false)
%}

%require "3.2"

%code requires {
#include "ast.hpp"
}

%define parse.error verbose
%locations

%union {
    int lex_token;
    bscp_value* value;
    bscp_obj* obj_value;
    bscp_num* num_value;
    bscp_null* null_value;
    bscp_list* list_value;

    std::string* word;
    std::string* punct;
}

%token <punct> EQUALS "="
%token <punct> PLUS_EQ "+="
%token <punct> INCREMENT "++"
%token <punct> MINUS_EQ "-="
%token <punct> DECREMENT "--"
%token <punct> STAR_EQ "*="
%token <punct> SLASH_EQ "/="
%token <punct> PERCENT_EQ "%="
%token <punct> AMPERSAND_EQ "&="
%token <punct> PIPE_EQ "|="
%token <punct> CARET_EQ "^="
%token <punct> LESS_EQ "<="
%token <punct> GREATER_EQ ">="
%token <punct> EQUAL_TO "=="
%token <punct> NOT_EQUAL_TO "!="
%token <punct> SHIFT_LEFT_EQ "<<="
%token <punct> SHIFT_RIGHT_EQ ">>="
%token <punct> LOGIC_AND "&&"
%token <punct> LOGIC_OR "||"
%token <punct> UNARY "!"
%token <punct> PLUS "+"
%token <punct> MINUS "-"
%token <punct> STAR "*"
%token <punct> SLASH "/"
%token <punct> PERCENT "%"
%token <punct> AMPERSAND "&"
%token <punct> BOR "|"
%token <punct> BNOT "~"
%token <punct> XOR "^"
%token <punct> LESS "<"
%token <punct> GREATER ">"
%token <punct> QUESTION_MARK "?"
%token <punct> COLON ":"
%token <punct> COMMA ","
%token <punct> DOT "."
%token <punct> SEMICOLON ";"
%token <punct> LPAREN "("
%token <punct> RPAREN ")"
%token <punct> LBRACKET "["
%token <punct> RBRACKET "]"
%token <punct> LBRACE "{"
%token <punct> RBRACE "}"
%token <punct> HASH "#"
%token <punct> SHL "<<"
%token <punct> SHR ">>"

%token <lex_token> lex_word
%token <lex_token> lex_number
%token <lex_token> lex_string
%token <lex_token> lex_eol
%token <lex_token> lex_assembly
%token <lex_token> lex_unknown

%right '=' "+=" "-=" "*=" "/=" "%=" "<<=" ">>=" "&=" "^=" "|="
%left ',' ';'
%right '?' ':'
%left "||"
%left "&&" 
%left '|'
%left '^'
%left '&'
%left "==" "!="
%left '<' "<=" '>' ">="
%left "<<" ">>"
%left '+' '-'
%left '*' '/' '%'
%right UNARY
%nonassoc '[' '.'

%type <value> expr start
%type <num_value> NUMBER
%type <obj_value> STRING
%type <word> WORD
%type <null_value> FIELD
%type <list_value> arg_list

%%
start: expr{
    output = $1;
    $$ = $1;
};

arg_list
    : %empty {
        $$ = new bscp_list({});
    }
    | expr {
        $$ = new bscp_list({$1});
    }
    | expr "," arg_list {
        ($3)->values.push_back($1);
        $$ = $3;
    }

expr
    : NUMBER { $$ = $1; }
    | STRING { $$ = $1; }
    | FIELD { $$ = $1; }
    | %empty { $$ = new bscp_null(nullptr); }
    | expr ";" expr {
        if(!dynamic_cast<bscp_null*>($1)){
            $$ = $3;
            delete $1;
        }else if(!dynamic_cast<bscp_null*>($3)){
            $$ = $1;
            delete $3;
        }else {
            ($3)->last = ($1);
            $$ = $3;
        }
    }
    | "(" expr ")" { $$ = $2; }
    | expr "." expr {
        require_true(dynamic_cast<bscp_obj*>($1), "Left operand of '.' must be an object");
        $$ = new bscp_oper(bscp_oper::OP_DOT, {$1, $3});
    }
    | expr "[" expr "]" {
        require_true(dynamic_cast<bscp_obj*>($1), "Left operand of '[]' must be an object");
        require_true(dynamic_cast<bscp_num*>($3), "Index must be a number");
        $$ = new bscp_oper(bscp_oper::OP_INDEX, {$1, $3});
    }
    | expr "." WORD {
        require_true(dynamic_cast<bscp_obj*>($1), "Left operand of '.' must be an object");
        $$ = new bscp_oper(bscp_oper::OP_DOT_WORD, {$1, new bscp_num(nullptr, *$3)});
    }
    | "!" expr %prec UNARY {
        $$ = new bscp_oper(bscp_oper::OP_UNARY_NOT, {$2});
    }
    | expr "==" expr {
        $$ = new bscp_oper(bscp_oper::OP_EQUAL_TO, {$1, $3});
    }
    | expr "!=" expr { 
        $$ = new bscp_oper(bscp_oper::OP_NOT_EQUAL_TO, {$1, $3});
    }
    | expr "&&" expr { 
        $$ = new bscp_oper(bscp_oper::OP_LOGICAL_AND, {$1, $3});
    }
    | expr "||" expr { 
        $$ = new bscp_oper(bscp_oper::OP_LOGICAL_OR, {$1, $3});
    }
    | expr "?" expr ":" expr { 
        $$ = new bscp_oper(bscp_oper::OP_TERNARY_CONDITIONAL, {$1, $3, $5});
    }
    | expr "=" expr {
        require_true(!$1->name.empty(), "Left operand must be assignable");
        $$ = new bscp_oper(bscp_oper::OP_ASSIGN, {$1, $3});
    }
    | "+" expr %prec UNARY { 
        require_true(dynamic_cast<bscp_num*>($2), "Operand of '+' must be a number");
        $$ = new bscp_oper(bscp_oper::OP_UNARY_PLUS, {$2});
    }
    | "-" expr %prec UNARY { 
        require_true(dynamic_cast<bscp_num*>($2), "Operand of '-' must be a number");
        $$ = new bscp_oper(bscp_oper::OP_UNARY_MINUS, {$2});
    }
    | "~" expr %prec UNARY { 
        require_true(dynamic_cast<bscp_num*>($2), "Operand of '~' must be a number");
        $$ = new bscp_oper(bscp_oper::OP_BITWISE_NOT, {$2});
    }
    | expr "*" expr { 
        require_true(dynamic_cast<bscp_num*>($1) && dynamic_cast<bscp_num*>($3), 
                   "Operands of '*' must be numbers");
        $$ = new bscp_oper(bscp_oper::OP_MULTIPLY, {$1, $3});
    }
    | expr "/" expr { 
        require_true(dynamic_cast<bscp_num*>($1) && dynamic_cast<bscp_num*>($3), 
                   "Operands of '/' must be numbers");
        $$ = new bscp_oper(bscp_oper::OP_DIVIDE, {$1, $3});
    }
    | expr "+" expr { 
        require_true(dynamic_cast<bscp_num*>($1) && dynamic_cast<bscp_num*>($3), 
                   "Operands of '+' must be numbers");
        $$ = new bscp_oper(bscp_oper::OP_PLUS, {$1, $3});
    }
    | expr "-" expr { 
        require_true(dynamic_cast<bscp_num*>($1) && dynamic_cast<bscp_num*>($3), 
                   "Operands of '-' must be numbers");
        $$ = new bscp_oper(bscp_oper::OP_MINUS, {$1, $3});
    }
    | expr "<" expr { 
        require_true(dynamic_cast<bscp_num*>($1) && dynamic_cast<bscp_num*>($3), 
                   "Operands of '<' must be numbers");
        $$ = new bscp_oper(bscp_oper::OP_LESS_THAN, {$1, $3});
    }
    | expr "<=" expr { 
        require_true(dynamic_cast<bscp_num*>($1) && dynamic_cast<bscp_num*>($3), 
                   "Operands of '<=' must be numbers");
        $$ = new bscp_oper(bscp_oper::OP_LESS_THAN_OR_EQUAL, {$1, $3});
    }
    | expr ">" expr { 
        require_true(dynamic_cast<bscp_num*>($1) && dynamic_cast<bscp_num*>($3), 
                   "Operands of '>' must be numbers");
        $$ = new bscp_oper(bscp_oper::OP_GREATER_THAN, {$1, $3});
    }
    | expr ">=" expr { 
        require_true(dynamic_cast<bscp_num*>($1) && dynamic_cast<bscp_num*>($3), 
                   "Operands of '>=' must be numbers");
        $$ = new bscp_oper(bscp_oper::OP_GREATER_THAN_OR_EQUAL, {$1, $3});
    }
    | expr "&" expr { 
        require_true(dynamic_cast<bscp_num*>($1) && dynamic_cast<bscp_num*>($3), 
                   "Operands of '&' must be numbers");
        $$ = new bscp_oper(bscp_oper::OP_BITWISE_AND, {$1, $3});
    }
    | expr "|" expr { 
        require_true(dynamic_cast<bscp_num*>($1) && dynamic_cast<bscp_num*>($3), 
                   "Operands of '|' must be numbers");
        $$ = new bscp_oper(bscp_oper::OP_BITWISE_OR, {$1, $3});
    }
    | expr "^" expr { 
        require_true(dynamic_cast<bscp_num*>($1) && dynamic_cast<bscp_num*>($3), 
                   "Operands of '^' must be numbers");
        $$ = new bscp_oper(bscp_oper::OP_BITWISE_XOR, {$1, $3});
    }
    | expr "+=" expr {
        require_true(dynamic_cast<bscp_num*>($1) && dynamic_cast<bscp_num*>($3), 
                   "Operands of '+=' must be numbers");
        $$ = new bscp_oper(bscp_oper::OP_ADD_ASSIGN, {$1, $3});
    }
    | expr "-=" expr {
        require_true(dynamic_cast<bscp_num*>($1) && dynamic_cast<bscp_num*>($3), 
                   "Operands of '-=' must be numbers");
        $$ = new bscp_oper(bscp_oper::OP_SUBTRACT_ASSIGN, {$1, $3});
    }
    | expr "*=" expr {
        require_true(dynamic_cast<bscp_num*>($1) && dynamic_cast<bscp_num*>($3), 
                   "Operands of '*=' must be numbers");
        $$ = new bscp_oper(bscp_oper::OP_MULTIPLY_ASSIGN, {$1, $3});
    }
    | expr "/=" expr {
        require_true(dynamic_cast<bscp_num*>($1) && dynamic_cast<bscp_num*>($3), 
                   "Operands of '/=' must be numbers");
        $$ = new bscp_oper(bscp_oper::OP_DIVIDE_ASSIGN, {$1, $3});
    }
    | expr "%=" expr {
        require_true(dynamic_cast<bscp_num*>($1) && dynamic_cast<bscp_num*>($3), 
                   "Operands of '%%=' must be numbers");
        $$ = new bscp_oper(bscp_oper::OP_MODULO_ASSIGN, {$1, $3});
    }
    | expr "<<=" expr {
        require_true(dynamic_cast<bscp_num*>($1) && dynamic_cast<bscp_num*>($3), 
                   "Operands of '<<=' must be numbers");
        $$ = new bscp_oper(bscp_oper::OP_SHIFT_LEFT_ASSIGN, {$1, $3});
    }
    | expr ">>=" expr {
        require_true(dynamic_cast<bscp_num*>($1) && dynamic_cast<bscp_num*>($3), 
                   "Operands of '>>=' must be numbers");
        $$ = new bscp_oper(bscp_oper::OP_SHIFT_RIGHT_ASSIGN, {$1, $3});
    }
    | expr "&=" expr {
        require_true(dynamic_cast<bscp_num*>($1) && dynamic_cast<bscp_num*>($3),
                   "Operands of '&=' must be numbers");
        $$ = new bscp_oper(bscp_oper::OP_BITWISE_AND_ASSIGN, {$1, $3});
    }
    | expr "|=" expr {
        require_true(dynamic_cast<bscp_num*>($1) && dynamic_cast<bscp_num*>($3),
                   "Operands of '|=' must be numbers");
        $$ = new bscp_oper(bscp_oper::OP_BITWISE_OR_ASSIGN, {$1, $3});
    }
    | expr "^=" expr {
        require_true(dynamic_cast<bscp_num*>($1) && dynamic_cast<bscp_num*>($3),
                   "Operands of '^=' must be numbers");
        $$ = new bscp_oper(bscp_oper::OP_BITWISE_XOR_ASSIGN, {$1, $3});
    }
    | expr "++" %prec INCREMENT {
        $$ = new bscp_oper(bscp_oper::OP_INCREMENT, {$1});
    }
    | expr "--" %prec DECREMENT {
        $$ = new bscp_oper(bscp_oper::OP_DECREMENT, {$1});
    }
    | "{" expr "}" { 
        $$ = new bscp_obj(nullptr);
    }
    | expr "(" arg_list ")" {
        std::vector<bscp_value*> values;
        values.push_back($1);
        for(auto arg : $3->values){
            values.push_back(arg);
        }
        $3->values = values;
        $$ = new bscp_oper(bscp_oper::OP_CALL_OBJ, $3);
    }
    ;

NUMBER: lex_number {
    std::string raw(current_token.raw, current_token.raw_size);
    $$ = new bscp_num(nullptr, raw);
};
FIELD: WORD {
    bscp_null* field = new bscp_null(nullptr); 
    field->name = *$1;
    $$ = field;
};
STRING: lex_string {
    bscp_obj* obj = new bscp_obj(nullptr);
    std::string raw(current_token.raw, current_token.raw_size);
    require_true(raw.size() >= 2 && raw[0] == '\"' && raw[raw.size() - 1] == '\"', "Invalid string constant");
    for(size_t i = 0; i < raw.size() - 2; i++) {
        std::string name = std::to_string(i);
        obj->static_fields.emplace(name, Field(*new bscp_num(obj, raw[i + 1]), false));
    }
    $$ = obj;
}
WORD: lex_word {
    $$ = new std::string(current_token.raw, current_token.raw_size);
}
%%

void yy::parser::error(const yy::parser::location_type &loc, const std::string &msg){
    fprintf(stderr, "%s:%d: error: %s\n", file_stack.top(), lexer->lineno(),msg.c_str());
}

int yylex(yy::parser::value_type* value, yy::parser::location_type* location) {
    lex_next(NULL);
    return current_token.type;
}
