%{
#include "bscp.hpp"

#include <typeinfo>
#include <string>
#include <math.h>
#include <map>
#include <cstring>

#ifndef FLEXLEXER_H
#include <FlexLexer.h>
#endif

#include "lex.hpp"

extern yyFlexLexer* lexer;

int yylex(yy::parser::value_type* value, yy::parser::location_type* location);

extern struct lex_token current_token;
extern std::shared_ptr<bscp::script::value> output;
namespace bscp::script
{
    extern int call_debug(std::shared_ptr<bscp::script::value> &value);
}

#define require_true(expr, ...) \
    do { \
        if(!(expr)) { \
            fprintf(stderr, __VA_ARGS__); \
            errno = 1; \
            YYERROR; \
        } \
    } while(false)
%}

%require "3.2"

%code requires {
#include "ast.hpp"
}

%define parse.error verbose
%locations

%union {
    int lex_token;
    std::shared_ptr<bscp::script::value> *value;
    std::shared_ptr<bscp::script::obj> *obj_value;
    std::shared_ptr<bscp::script::num> *num_value;
    std::shared_ptr<bscp::script::null> *null_value; 
    std::shared_ptr<bscp::script::field> *field_value;
    std::shared_ptr<bscp::script::list> *list_value;

    std::wstring* word;
    std::wstring* punct;
}

%token <punct> EQUALS "="
%token <punct> PLUS_EQ "+="
%token <punct> INCREMENT "++"
%token <punct> MINUS_EQ "-="
%token <punct> DECREMENT "--"
%token <punct> STAR_EQ "*="
%token <punct> SLASH_EQ "/="
%token <punct> PERCENT_EQ "%="
%token <punct> AMPERSAND_EQ "&="
%token <punct> PIPE_EQ "|="
%token <punct> CARET_EQ "^="
%token <punct> LESS_EQ "<="
%token <punct> GREATER_EQ ">="
%token <punct> EQUAL_TO "=="
%token <punct> NOT_EQUAL_TO "!="
%token <punct> SHIFT_LEFT_EQ "<<="
%token <punct> SHIFT_RIGHT_EQ ">>="
%token <punct> LOGIC_AND "&&"
%token <punct> LOGIC_OR "||"
%token <punct> UNARY "!"
%token <punct> PLUS "+"
%token <punct> MINUS "-"
%token <punct> STAR "*"
%token <punct> SLASH "/"
%token <punct> PERCENT "%"
%token <punct> AMPERSAND "&"
%token <punct> BOR "|"
%token <punct> BNOT "~"
%token <punct> XOR "^"
%token <punct> LESS "<"
%token <punct> GREATER ">"
%token <punct> QUESTION_MARK "?"
%token <punct> COLON ":"
%token <punct> COMMA ","
%token <punct> DOT "."
%token <punct> SEMICOLON ";"
%token <punct> LPAREN "("
%token <punct> RPAREN ")"
%token <punct> LBRACKET "["
%token <punct> RBRACKET "]"
%token <punct> LBRACE "{"
%token <punct> RBRACE "}"
%token <punct> HASH "#"
%token <punct> SHL "<<"
%token <punct> SHR ">>"

%token <lex_token> lex_word
%token <lex_token> lex_integer
%token <lex_token> lex_char
%token <lex_token> lex_decimal
%token <lex_token> lex_string
%token <lex_token> lex_eol
%token <lex_token> lex_assembly
%token <lex_token> lex_unknown
/* 
%left SUFF_INC SUFF_DEC
%nonassoc "(" "[" "." 
%right PREF_INC PREF_DEC POSITATE NEGATE "!" "~"
%left "*" "/" "%"
%left "+" "-"
%left "<<" ">>"
%left "<" "<=" ">" ">="
%left "==" "!="
%left "&"
%left "^"
%left "|"
%left "&&"
%left "||"
%right "?" ":"
%right "=" "+=" "-=" "*=" "/=" "%=" "<<=" ">>=" "&=" "^=" "|="
%left "," */



%left ","
%right "=" "+=" "-=" "*=" "/=" "%=" "<<=" ">>=" "&=" "^=" "|="
%right "?" ":"
%left "||"
%left "&&"
%left "|"
%left "^"
%left "&"
%left "==" "!="
%left "<" "<=" ">" ">="
%left "<<" ">>"
%left "+" "-"
%left "*" "/" "%"
%right "++" "--" POSITATE NEGATE "!" "~"
%nonassoc "(" "[" "." 
%left SUFF_INC SUFF_DEC


%type <value> expr start
%type <num_value> number INTEGER DECIMAL CHAR
%type <obj_value> STRING object
%type <word> WORD
%type <field_value> field
%type <list_value> arg_list expr_list

%%
start: expr_list {
    auto obj = std::make_shared<bscp::script::obj>(nullptr);
    obj->parent = obj;
    for(auto i=(*$1)->values.rbegin(); i!=(*$1)->values.rend(); i++){
        (*i)->parent = obj;
        obj->lines.emplace_back(*i);
    }
    output = obj;
    $$ = &output;
};

arg_list
    : %empty {
        $$ = new std::shared_ptr<bscp::script::list>(new bscp::script::list({}));
    }
    | expr {
        $$ = new std::shared_ptr<bscp::script::list>(new bscp::script::list({std::shared_ptr<bscp::script::value>(*$1)}));
    }
    | expr "," arg_list {
        (*$3)->values.emplace_back(*$1);
        $$ = $3;
    }
expr_list
    : %empty {
        $$ = new std::shared_ptr<bscp::script::list>(new bscp::script::list({}));
    }
    | expr {
        $$ = new std::shared_ptr<bscp::script::list>(new bscp::script::list({std::shared_ptr<bscp::script::value>(*$1)}));
    }
    | expr ";" expr_list {
        (*$3)->values.emplace_back(*$1);
        $$ = $3;
    }
expr
    : number { $$ = new std::shared_ptr<bscp::script::value>(std::dynamic_pointer_cast<bscp::script::value>(*$1)); }
    | STRING { $$ = new std::shared_ptr<bscp::script::value>(std::dynamic_pointer_cast<bscp::script::value>(*$1)); }
    | field { $$ = new std::shared_ptr<bscp::script::value>(std::dynamic_pointer_cast<bscp::script::value>(*$1)); }
    | "(" expr ")" { $$ = $2; }
    | expr "." expr {
        require_true(std::dynamic_pointer_cast<bscp::script::obj>(*$1), "Left operand of '.' must be an object");
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_DOT, {*$1, *$3}));
    }
    | expr "[" expr "]" {
        require_true(std::dynamic_pointer_cast<bscp::script::obj>(*$1), "Left operand of '[]' must be an object");
        require_true(std::dynamic_pointer_cast<bscp::script::num>(*$3), "Index must be a number");
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_INDEX, {*$1, *$3}));
    }
    /* | expr "." WORD {
        require_true(std::dynamic_pointer_cast<bscp::script::obj>(*$1), "Left operand of '.' must be an object");
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_DOT_WORD, {*$1, std::shared_ptr<bscp::script::value>(new bscp::script::num(nullptr, *$3))}));
    } */
    | "!" expr {
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_UNARY_NOT, {*$2}));
    }
    | expr "==" expr {
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_EQUAL_TO, {*$1, *$3}));
    }
    | expr "!=" expr { 
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_NOT_EQUAL_TO, {*$1, *$3}));
    }
    | expr "&&" expr { 
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_LOGICAL_AND, {*$1, *$3}));
    }
    | expr "||" expr { 
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_LOGICAL_OR, {*$1, *$3}));
    }
    | expr "?" expr ":" expr { 
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_TERNARY_CONDITIONAL, {*$1, *$3, *$5}));
    }
    | expr "=" expr {
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_ASSIGN, {*$1, *$3}));
    }
    | "+" expr %prec POSITATE { 
        require_true(std::dynamic_pointer_cast<bscp::script::num>(*$2), "Operand of '+' must be a number");
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_UNARY_PLUS, {*$2}));
    }
    | "-" expr %prec NEGATE { 
        require_true(std::dynamic_pointer_cast<bscp::script::num>(*$2), "Operand of '-' must be a number");
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_UNARY_MINUS, {*$2}));
    }
    | "~" expr { 
        require_true(std::dynamic_pointer_cast<bscp::script::num>(*$2), "Operand of '~' must be a number");
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_BITWISE_NOT, {*$2}));
    }
    | expr "*" expr { 
        require_true(std::dynamic_pointer_cast<bscp::script::num>(*$1) && std::dynamic_pointer_cast<bscp::script::num>(*$3), 
                   "Operands of '*' must be numbers");
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_MULTIPLY, {*$1, *$3}));
    }
    | expr "/" expr { 
        require_true(std::dynamic_pointer_cast<bscp::script::num>(*$1) && std::dynamic_pointer_cast<bscp::script::num>(*$3), 
                   "Operands of '/' must be numbers");
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_DIVIDE, {*$1, *$3}));
    }
    | expr "+" expr { 
        require_true(std::dynamic_pointer_cast<bscp::script::num>(*$1) && std::dynamic_pointer_cast<bscp::script::num>(*$3), 
                   "Operands of '+' must be numbers");
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_PLUS, {*$1, *$3}));
    }
    | expr "-" expr { 
        require_true(std::dynamic_pointer_cast<bscp::script::num>(*$1) && std::dynamic_pointer_cast<bscp::script::num>(*$3), 
                   "Operands of '-' must be numbers");
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_MINUS, {*$1, *$3}));
    }
    | expr "<" expr { 
        require_true(std::dynamic_pointer_cast<bscp::script::num>(*$1) && std::dynamic_pointer_cast<bscp::script::num>(*$3), 
                   "Operands of '<' must be numbers");
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_LESS_THAN, {*$1, *$3}));
    }
    | expr "<=" expr { 
        require_true(std::dynamic_pointer_cast<bscp::script::num>(*$1) && std::dynamic_pointer_cast<bscp::script::num>(*$3), 
                   "Operands of '<=' must be numbers");
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_LESS_THAN_OR_EQUAL, {*$1, *$3}));
    }
    | expr ">" expr { 
        require_true(std::dynamic_pointer_cast<bscp::script::num>(*$1) && std::dynamic_pointer_cast<bscp::script::num>(*$3), 
                   "Operands of '>' must be numbers");
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_GREATER_THAN, {*$1, *$3}));
    }
    | expr ">=" expr { 
        require_true(std::dynamic_pointer_cast<bscp::script::num>(*$1) && std::dynamic_pointer_cast<bscp::script::num>(*$3), 
                   "Operands of '>=' must be numbers");
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_GREATER_THAN_OR_EQUAL, {*$1, *$3}));
    }
    | expr "&" expr { 
        require_true(std::dynamic_pointer_cast<bscp::script::num>(*$1) && std::dynamic_pointer_cast<bscp::script::num>(*$3), 
                   "Operands of '&' must be numbers");
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_BITWISE_AND, {*$1, *$3}));
    }
    | expr "|" expr { 
        require_true(std::dynamic_pointer_cast<bscp::script::num>(*$1) && std::dynamic_pointer_cast<bscp::script::num>(*$3), 
                   "Operands of '|' must be numbers");
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_BITWISE_OR, {*$1, *$3}));
    }
    | expr "^" expr { 
        require_true(std::dynamic_pointer_cast<bscp::script::num>(*$1) && std::dynamic_pointer_cast<bscp::script::num>(*$3), 
                   "Operands of '^' must be numbers");
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_BITWISE_XOR, {*$1, *$3}));
    }
    | expr "+=" expr {
        require_true(std::dynamic_pointer_cast<bscp::script::num>(*$1) && std::dynamic_pointer_cast<bscp::script::num>(*$3), 
                   "Operands of '+=' must be numbers");
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_ADD_ASSIGN, {*$1, *$3}));
    }
    | expr "-=" expr {
        require_true(std::dynamic_pointer_cast<bscp::script::num>(*$1) && std::dynamic_pointer_cast<bscp::script::num>(*$3), 
                   "Operands of '-=' must be numbers");
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_SUBTRACT_ASSIGN, {*$1, *$3}));
    }
    | expr "*=" expr {
        require_true(std::dynamic_pointer_cast<bscp::script::num>(*$1) && std::dynamic_pointer_cast<bscp::script::num>(*$3), 
                   "Operands of '*=' must be numbers");
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_MULTIPLY_ASSIGN, {*$1, *$3}));
    }
    | expr "/=" expr {
        require_true(std::dynamic_pointer_cast<bscp::script::num>(*$1) && std::dynamic_pointer_cast<bscp::script::num>(*$3), 
                   "Operands of '/=' must be numbers");
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_DIVIDE_ASSIGN, {*$1, *$3}));
    }
    | expr "%=" expr {
        require_true(std::dynamic_pointer_cast<bscp::script::num>(*$1) && std::dynamic_pointer_cast<bscp::script::num>(*$3), 
                   "Operands of '%%=' must be numbers");
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_MODULO_ASSIGN, {*$1, *$3}));
    }
    | expr "<<=" expr {
        require_true(std::dynamic_pointer_cast<bscp::script::num>(*$1) && std::dynamic_pointer_cast<bscp::script::num>(*$3), 
                   "Operands of '<<=' must be numbers");
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_SHIFT_LEFT_ASSIGN, {*$1, *$3}));
    }
    | expr ">>=" expr {
        require_true(std::dynamic_pointer_cast<bscp::script::num>(*$1) && std::dynamic_pointer_cast<bscp::script::num>(*$3), 
                   "Operands of '>>=' must be numbers");
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_SHIFT_RIGHT_ASSIGN, {*$1, *$3}));
    }
    | expr "&=" expr {
        require_true(std::dynamic_pointer_cast<bscp::script::num>(*$1) && std::dynamic_pointer_cast<bscp::script::num>(*$3),
                   "Operands of '&=' must be numbers");
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_BITWISE_AND_ASSIGN, {*$1, *$3}));
    }
    | expr "|=" expr {
        require_true(std::dynamic_pointer_cast<bscp::script::num>(*$1) && std::dynamic_pointer_cast<bscp::script::num>(*$3),
                   "Operands of '|=' must be numbers");
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_BITWISE_OR_ASSIGN, {*$1, *$3}));
    }
    | expr "^=" expr {
        require_true(std::dynamic_pointer_cast<bscp::script::num>(*$1) && std::dynamic_pointer_cast<bscp::script::num>(*$3),
                   "Operands of '^=' must be numbers");
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_BITWISE_XOR_ASSIGN, {*$1, *$3}));
    }
    | expr "++" %prec SUFF_INC {
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_GET_INCREMENT, {*$1}));
    }
    | expr "--" %prec SUFF_DEC {
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_GET_DECREMENT, {*$1}));
    }
    | "++" expr {
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_INCREMENT_GET, {*$2}));
    }
    | "--" expr {
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_DECREMENT_GET, {*$2}));
    }
    | expr "(" arg_list ")" {
        std::vector<std::shared_ptr<bscp::script::value>> values;
        values.emplace_back(*$1);
        for(auto arg : (*$3)->values){
            values.emplace_back(arg);
        }
        (*$3)->values = values;
        $$ = new std::shared_ptr<bscp::script::value>(new bscp::script::oper(bscp::script::oper::OP_CALL_OBJ, *$3));
    }
    | object { $$ = new std::shared_ptr<bscp::script::value>(*$1); }
    ;
object: "{" expr_list "}" {
    auto obj = std::make_shared<bscp::script::obj>(nullptr);
    for(auto i=(*$2)->values.rbegin(); i!=(*$2)->values.rend(); i++){
        (*i)->parent = obj;
        obj->lines.emplace_back(*i);
    }
    $$ = new std::shared_ptr<bscp::script::obj>(obj);
}
INTEGER: lex_integer {
    std::wstring raw(current_token.raw, current_token.raw_size);
    $$ = new std::shared_ptr<bscp::script::num>(new bscp::script::num(nullptr, raw));
};
DECIMAL: lex_decimal {
    std::wstring raw(current_token.raw, current_token.raw_size);
    $$ = new std::shared_ptr<bscp::script::num>(new bscp::script::num(nullptr, raw));
};
CHAR: lex_char {
    require_true((
        current_token.raw_size > 2 && 
        current_token.raw[0] == '\'' &&
        current_token.raw[current_token.raw_size - 1] == '\''
    ), "Invalid char constant");
    std::wstring raw(current_token.raw+1, current_token.raw_size - 2);
    $$ = new std::shared_ptr<bscp::script::num>(bscp::script::format_chr_const(raw));
};
number: INTEGER | DECIMAL | CHAR;

field
    : WORD {
        bscp::script::field* field = new bscp::script::field(nullptr, true);
        field->name = *$1;
        $$ = new std::shared_ptr<bscp::script::field>(field);
    }
    | "." WORD {
        bscp::script::field* field = new bscp::script::field(nullptr, false);
        field->name = *$2;
        $$ = new std::shared_ptr<bscp::script::field>(field);
    }
    | "." INTEGER {
        bscp::script::field* field = new bscp::script::field(nullptr, false);
        field->name = std::to_wstring((unsigned long long int)(*$2)->value);
        $$ = new std::shared_ptr<bscp::script::field>(field);
    }
    ;
STRING: lex_string {
    require_true((
        current_token.raw_size > 2 && 
        current_token.raw[0] == '\"' &&
        current_token.raw[current_token.raw_size - 1] == '\"'
    ), "Invalid char constant");
    std::wstring raw(current_token.raw+1, current_token.raw_size-2);
    $$ = new std::shared_ptr<bscp::script::obj>(bscp::script::format_str_const(raw));
}
WORD: lex_word {
    $$ = new std::wstring(current_token.raw, current_token.raw_size);
}
%%

void yy::parser::error(const yy::parser::location_type &loc, const std::string &msg){
    fwprintf(stderr, L"%s:%d: error: %s\n", file_stack.top(), lexer->lineno(),msg.c_str());
}

int yylex(yy::parser::value_type* value, yy::parser::location_type* location) {
    lex_next(NULL);
    return current_token.type;
}
