#!./bscp

# comments
// comments
/* comments */
/** comments */

# hello world
print("hello world\n");
debug("yellow world\n");

print("\n--------\n");

# local & static variable
text = "text0";
.text = "g_text";

print("text: ");
print(text);
print("\n");

print(".text: ");
print(.text);
print("\n");

# objects
print("\n--------\n");
aaa = {
    .0=97;
    .1=97;
    .2=97;
    .3=97;
    .4=97;
    .5="\n"[0]-1+1;
};
bbb = ['b',98,98,98,98,'\n'];
print(aaa);
print(bbb);
